worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;
    include /etc/nginx/mime.types;

    upstream frontend {
        server frontend:80;
    }

    upstream auth_service {
        server auth-service:8000;
    }

    upstream inventory_service {
        server inventory-service:4000;
    }

    server {
        listen 80;
        server_name localhost;

        # 공통 헤더 (CORS 방지)
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE";
        add_header Access-Control-Allow-Headers "Content-Type, Authorization";

        # OPTIONS 요청 핸들링
        if ($request_method = OPTIONS) {
            return 204;
        }

        # Frontend 라우팅
        location / {
            proxy_pass http://frontend;
        }

        # Auth Service
        location /auth/ {
            rewrite ^/auth/(.*)$ /$1 break;
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Inventory Service
        location /inv/ {
            rewrite ^/inv/(.*)$ /$1 break;
            proxy_pass http://inventory_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
